web:
  image: nginx
  ports:
   - "8000:80"
  volumes:
   - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
   - .:/srv
  links:
   - php

php:
  build: .
  volumes:
   - .:/srv
  links:
   - mysql

mysql:
  image: mysql
  env_file: .env
